apiVersion: v1
kind: Service
metadata:
  name: service-clusterip
spec:
  selector:
    app: mysql-deploy
  type: ClusterIP
  ports: 
    - protocol: TCP
      port: 3306
      targetPort: 3306
      
     

